config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :categories, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "home", to: "home#index"

  get "password", to: "passwords#edit" , as: :edit_password

  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"

  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"

  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"

  post "password/reset", to: "password_resets#create"

  root "main#index"

  get "about", to: "home#about"

  get "index", to: "cart_items#index"
  
  # post "cart" to: "shopping_carts#create"
  # get "author", to: "author#index"
  get "show", to: "author#show"
  
  resources :books do
    resources :cart_items, only: [:create]
  end

 # config/routes.rb
  resources :cart_items, only: [:create]
  
  

  resource :shopping_carts, only: [:show]
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role=="alert"> 
    <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
    <!-- Footer -->

    <footer class="text-center text-white fixed-bottom" style="background-color: #0a4275;">

      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);" >
        © 2020 Copyright:
        <a class="text-white" href="http://localhost:3000/home">Bookify</a>
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #32434d; opacity: 0.9;">
    <div class="container-fluid">
      <%= image_tag "png.png", {height: 30} %>
      <h4>
      <%= link_to "Bookify", books_path, class: "navbar-brand p-t-2" %>
      </h4>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <!-- <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/home">Home</a>
          </li> -->
          <h6>
            <li class="nav-item">
              <%= link_to "Books", books_path, class: "nav-link navbar_items p-t-2" %>
            </li>
          </h6> 
          <h6>
          <li class="nav-item">
            <%= link_to "My Cart", cart_items_path, class: "nav-link navbar_items p-t-2" %>
          </li>
          </h6>
          <h6>
          <li class="nav-item">
            <%= link_to "About Us", about_path, class: "nav-link navbar_items p-t-2" %>
          </li>
          </h6>
        </ul>
         
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if Current.user %>
          <strong>
              <li class="nav-item">
                <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
              </li>
          </strong>
              &nbsp &nbsp
              
              <li class="nav-item">
                <i class="bi bi-cart-fill"></i>
              </li>
              <li class="nav-item">
                <%= button_to "logout", logout_path, method: :delete, class: "btn btn-outline-danger" %>
              </li>
          <% else %>
          <strong>
              <li class="nav-item">
                <%= link_to "Sign Up",sign_up_path, class: "nav-link" %>
              </li>
          </strong>
          <strong>
              <li class="nav-item">
                <%= link_to "Login",sign_in_path, class: "nav-link btn-secondary"%>
              </li>
          </strong>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>