config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :categories, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "home", to: "home#index"

  get "password", to: "passwords#edit" , as: :edit_password

  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"

  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"

  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"

  post "password/reset", to: "password_resets#create"

  root "main#index"

  get "about", to: "home#about"

  get "index", to: "cart_items#index"
  
  # post "cart" to: "shopping_carts#create"
  # get "author", to: "author#index"
  get "show", to: "author#show"
  
  resources :books do
    resources :cart_items, only: [:create]
  end

 # config/routes.rb
  resources :cart_items, only: [:create]
  
  

  resource :shopping_carts, only: [:show]
end

app/models/cart_item.rb
# class CartItem < ApplicationRecord
#   belongs_to :book
#   belongs_to :shopping_cart

#   # validates :quantity numericality: {only-integer: true, greater_than: 0}

#   # app/models/cartitem.rb

#   def total_price
#     book.price * quantity
#   end

# end

# app/models/cart_item.rb

class CartItem < ApplicationRecord
  belongs_to :book
  belongs_to :shopping_carts
  
  def subtotal
    quantity * book.price
  end
end

app/controllers/cart_items_controller.rb
# app/controllers/cart_items_controller.rb

# class CartItemsController < ApplicationController
#   # def create
#   #   @book = Book.find(params[:book_id])
#   #   current_cart.add_item(@book)
#   #   redirect_to cart_path
#   # end
  
#   # def destroy
#   #   @book = Book.find(params[:id])
#   #   current_cart.remove_item(@book)
#   #   redirect_to cart_path
#   # end
# end

# app/controllers/cart_items_controller.rb

class CartItemsController < ApplicationController

  def index
    @cart_items = current_cart.cart_items
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end
   
  def create
    @book = Book.find(book_id)
    current_cart.add_item(@book)
    redirect_to shopping_carts_path
  end
  
  def update
    @book = Book.find(book_id)
    current_cart.update_item_quantity(@book, params[:quantity].to_i)
    redirect_to shopping_carts_path
  end

  def destroy
    @book = Book.find(book_id)
    current_cart.remove_item(@book)
    redirect_to shopping_carts_path
  end
end

app/views/cart_items/edit.html.erb
<h1>Edit Cart Item</h1>
 
<%= form_for @cart_item, url: cart_item_path(@cart_item), method: :patch do |f| %>
  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, class: "form-control" %>
  </div>
 
  <%= f.submit "Update Cart Item", class: "btn btn-primary" %>
<% end %>

app/views/cart_items/index.html.erb
<h1 style="color:azure">Shopping Cart</h1>

<% @cart_items.each do |item| %>
  <p><%= item.book.title %> - <%= item.quantity %> - <%= item.book.price %></p>
<% end %>

<p>Total Price: <%= @total_price %></p>

app/views/cart_items/new.html.erb
<h1>Add to Cart</h1>
 
<%= form_for @cart_item, url: cart_items_path do |f| %>
  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, class: "form-sm", value: 1, min: 1 %>
  </div>
 
  <%= f.hidden_field :book_id %>
 
  <%= f.submit "Add to Cart", class: "btn btn-primary" %>
<% end %>